//! Persisted grammar paradigms and their applicability rules.
//!
//! This deliberately does not reuse `phonology_tables::Body`: the grid shape is
//! familiar, but a grammar cell is executable Lexurgy source rather than a list
//! of phonemes. Keeping the JSON types separate makes that boundary explicit.

use std::collections::HashSet;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::{FromRow, Row};
use uuid::Uuid;

use crate::{
    err::{AppResult, bad_request, forbidden},
    model::{
        language_invites::PermissionLevel, language_permissions::LanguagePermissionRepository,
        languages::Language, user_bans::UserBanRepository, users::User, words::Word,
    },
    util::AppState,
};

const MAX_DEPTH: usize = 6;
const MAX_LEAF_ROWS: usize = 50;
const MAX_LEAF_COLUMNS: usize = 50;
const MAX_CELLS: usize = MAX_LEAF_ROWS * MAX_LEAF_COLUMNS;
const MAX_UNIQUE_PROGRAMS: usize = 256;
const MAX_PREAMBLE_BYTES: usize = 32 * 1024;
const MAX_CELL_BYTES: usize = 16 * 1024;
const MAX_PROGRAM_BYTES: usize = 256 * 1024;

fn ensure_unique_ids(ids: &[Uuid], resource_name: &str) -> AppResult<()> {
    if ids.iter().collect::<HashSet<_>>().len() != ids.len() {
        return Err(bad_request(format!(
            "A grammar table cannot select the same {resource_name} more than once."
        )));
    }
    Ok(())
}

fn span_default() -> u32 {
    1
}
fn span_is_default(value: &u32) -> bool {
    *value == 1
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GrammarCell {
    #[serde(default)]
    pub changes: String,
    #[serde(default = "span_default", skip_serializing_if = "span_is_default")]
    pub rowspan: u32,
    #[serde(default = "span_default", skip_serializing_if = "span_is_default")]
    pub colspan: u32,
}

impl Default for GrammarCell {
    fn default() -> Self {
        Self {
            changes: String::new(),
            rowspan: 1,
            colspan: 1,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum GrammarRow {
    Group {
        heading: String,
        #[serde(default)]
        autogenerated: bool,
        rows: Vec<GrammarRow>,
    },
    Individual {
        heading: String,
        #[serde(default)]
        autogenerated: bool,
        cells: Vec<GrammarCell>,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum GrammarColumn {
    Group {
        heading: String,
        #[serde(default)]
        autogenerated: bool,
        columns: Vec<GrammarColumn>,
    },
    Individual {
        heading: String,
        #[serde(default)]
        autogenerated: bool,
    },
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GrammarBody {
    #[serde(default)]
    pub rows: Vec<GrammarRow>,
    #[serde(default)]
    pub columns: Vec<GrammarColumn>,
}

impl GrammarBody {
    pub fn validate(&self, preamble: &str) -> AppResult<()> {
        fn count_columns(columns: &[GrammarColumn], depth: usize) -> AppResult<usize> {
            if depth > MAX_DEPTH {
                return Err(bad_request(
                    "Grammar table headings may be at most 6 levels deep.",
                ));
            }
            let mut total = 0;
            for column in columns {
                total += match column {
                    GrammarColumn::Individual { .. } => 1,
                    GrammarColumn::Group { columns, .. } => count_columns(columns, depth + 1)?,
                };
            }
            Ok(total)
        }
        fn leaf_rows<'a>(
            rows: &'a [GrammarRow],
            depth: usize,
            out: &mut Vec<&'a [GrammarCell]>,
        ) -> AppResult<()> {
            if depth > MAX_DEPTH {
                return Err(bad_request(
                    "Grammar table headings may be at most 6 levels deep.",
                ));
            }
            for row in rows {
                match row {
                    GrammarRow::Group { rows, .. } => leaf_rows(rows, depth + 1, out)?,
                    GrammarRow::Individual { cells, .. } => out.push(cells),
                }
            }
            Ok(())
        }

        if preamble.len() > MAX_PREAMBLE_BYTES {
            return Err(bad_request(
                "Grammar table preamble must be at most 32 KiB.",
            ));
        }
        let column_count = count_columns(&self.columns, 1)?;
        if column_count == 0 {
            return Err(bad_request("Grammar tables need at least one column."));
        }
        if column_count > MAX_LEAF_COLUMNS {
            return Err(bad_request(
                "Grammar tables may have at most 50 leaf columns.",
            ));
        }
        let mut rows = Vec::new();
        leaf_rows(&self.rows, 1, &mut rows)?;
        if rows.is_empty() {
            return Err(bad_request("Grammar tables need at least one row."));
        }
        if rows.len() > MAX_LEAF_ROWS {
            return Err(bad_request("Grammar tables may have at most 50 leaf rows."));
        }
        if rows.len() * column_count > MAX_CELLS {
            return Err(bad_request("Grammar tables may have at most 2,500 cells."));
        }

        let mut occupied = vec![vec![false; column_count]; rows.len()];
        let mut programs = HashSet::new();
        let mut program_bytes = 0usize;
        for (row_index, cells) in rows.iter().enumerate() {
            if cells.len() != column_count {
                return Err(bad_request(format!(
                    "Each row must have {column_count} cells."
                )));
            }
            for (column_index, cell) in cells.iter().enumerate() {
                if cell.changes.len() > MAX_CELL_BYTES {
                    return Err(bad_request("Grammar cell rules must be at most 16 KiB."));
                }
                if cell.rowspan == 0 || cell.colspan == 0 {
                    return Err(bad_request("Cell rowspan and colspan must be at least 1."));
                }
                if occupied[row_index][column_index] {
                    if !cell.changes.trim().is_empty() || cell.rowspan != 1 || cell.colspan != 1 {
                        return Err(bad_request(
                            "Cells covered by a merged cell must have empty rules and a 1×1 span.",
                        ));
                    }
                    continue;
                }
                let row_end = row_index + cell.rowspan as usize;
                let column_end = column_index + cell.colspan as usize;
                if row_end > rows.len() || column_end > column_count {
                    return Err(bad_request(
                        "Merged cells cannot extend past the edge of the table.",
                    ));
                }
                for occupied_row in occupied.iter_mut().take(row_end).skip(row_index) {
                    for slot in occupied_row.iter_mut().take(column_end).skip(column_index) {
                        if *slot {
                            return Err(bad_request("Merged cells cannot overlap each other."));
                        }
                        *slot = true;
                    }
                }
                let program = compose_changes(preamble, &cell.changes);
                if programs.insert(program.clone()) {
                    program_bytes += program.len();
                }
            }
        }
        if programs.len() > MAX_UNIQUE_PROGRAMS {
            return Err(bad_request(
                "Grammar tables may have at most 256 unique rule programs.",
            ));
        }
        if program_bytes > MAX_PROGRAM_BYTES {
            return Err(bad_request(
                "Grammar table programs may total at most 256 KiB.",
            ));
        }
        Ok(())
    }

    pub fn visible_cells(&self) -> Vec<(usize, usize, &GrammarCell)> {
        fn collect<'a>(rows: &'a [GrammarRow], out: &mut Vec<&'a [GrammarCell]>) {
            for row in rows {
                match row {
                    GrammarRow::Group { rows, .. } => collect(rows, out),
                    GrammarRow::Individual { cells, .. } => out.push(cells),
                }
            }
        }
        let mut rows = Vec::new();
        collect(&self.rows, &mut rows);
        let mut covered = HashSet::new();
        let mut output = Vec::new();
        for (r, cells) in rows.iter().enumerate() {
            for (c, cell) in cells.iter().enumerate() {
                if covered.contains(&(r, c)) {
                    continue;
                }
                for dr in 0..cell.rowspan as usize {
                    for dc in 0..cell.colspan as usize {
                        if dr != 0 || dc != 0 {
                            covered.insert((r + dr, c + dc));
                        }
                    }
                }
                output.push((r, c, cell));
            }
        }
        output
    }
}

pub fn compose_changes(preamble: &str, changes: &str) -> String {
    match (preamble.trim(), changes.trim()) {
        ("", "") => String::new(),
        ("", changes) => changes.to_string(),
        (preamble, "") => preamble.to_string(),
        (preamble, changes) => format!("{preamble}\n{changes}"),
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct GrammarTable {
    pub id: Uuid,
    #[serde(skip_serializing)]
    pub language_id: Uuid,
    pub name: String,
    pub description: String,
    pub preamble: String,
    pub body: Value,
    pub position: i32,
    pub schema_version: i32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(skip_serializing)]
    pub created_by: Option<Uuid>,
    #[serde(skip_serializing)]
    pub updated_by: Option<Uuid>,
    #[serde(default)]
    #[sqlx(default)]
    pub word_class_ids: Vec<Uuid>,
    #[serde(default)]
    #[sqlx(default)]
    pub category_ids: Vec<Uuid>,
}

pub struct GrammarTableExample {
    pub word: Word,
    pub first_definition: Option<String>,
}

impl GrammarTable {
    pub fn body(&self) -> AppResult<GrammarBody> {
        let body: GrammarBody = serde_json::from_value(self.body.clone())?;
        body.validate(&self.preamble)?;
        Ok(body)
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct CreateGrammarTable {
    #[serde(default)]
    pub language_id: Uuid,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub preamble: String,
    pub body: GrammarBody,
    pub word_class_ids: Vec<Uuid>,
    #[serde(default)]
    pub category_ids: Vec<Uuid>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct UpdateGrammarTable {
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub preamble: String,
    pub body: GrammarBody,
    pub word_class_ids: Vec<Uuid>,
    #[serde(default)]
    pub category_ids: Vec<Uuid>,
}

#[derive(Clone)]
pub struct GrammarTableRepository {
    state: AppState,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GrammarCacheKey {
    pub runner_version: i32,
    pub source_kind: String,
    pub changes_hash: String,
    pub input_word: String,
}

#[derive(Debug, FromRow)]
struct GrammarCacheEntry {
    changes_hash: String,
    output_word: String,
}

impl GrammarTableRepository {
    pub fn new(state: AppState) -> Self {
        Self { state }
    }

    async fn validate_scope(
        &self,
        language_id: Uuid,
        classes: &[Uuid],
        categories: &[Uuid],
    ) -> AppResult<()> {
        ensure_unique_ids(classes, "word class")?;
        ensure_unique_ids(categories, "category")?;
        if classes.is_empty() {
            return Err(bad_request(
                "A grammar table needs at least one word class.",
            ));
        }
        let class_count: i64 = sqlx::query_scalar(
            "select count(*) from word_classes where language = $1 and id = any($2)",
        )
        .bind(language_id)
        .bind(classes)
        .fetch_one(&self.state.pool)
        .await?;
        if class_count != classes.iter().collect::<HashSet<_>>().len() as i64 {
            return Err(bad_request(
                "Every selected word class must belong to this language.",
            ));
        }
        let category_count: i64 = sqlx::query_scalar(
            "select count(*) from word_categories where language = $1 and id = any($2)",
        )
        .bind(language_id)
        .bind(categories)
        .fetch_one(&self.state.pool)
        .await?;
        if category_count != categories.iter().collect::<HashSet<_>>().len() as i64 {
            return Err(bad_request(
                "Every selected category must belong to this language.",
            ));
        }
        Ok(())
    }

    async fn check_editor_with_audit(
        &self,
        requestor: &User,
        language_id: Uuid,
        action_type: crate::model::audit_log::AuditActionType,
        resource_id: Uuid,
        context: serde_json::Value,
        denied_action: &str,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    ) -> AppResult<()> {
        use crate::model::{
            audit_log::{AuditableResource, PermissionCheck},
            language_permissions::CheckPermissionReq,
        };

        let permission = LanguagePermissionRepository::new(self.state.clone())
            .check_permission_with_audit(
                CheckPermissionReq {
                    user: requestor.id,
                    language: language_id,
                    required_level: PermissionLevel::Editor,
                    action_type,
                    resource_type: AuditableResource::GrammarTable,
                    resource_id,
                    context: Some(context),
                },
                tx,
            )
            .await?;
        if permission == PermissionCheck::NoPermission {
            return Err(forbidden(format!(
                "You do not have permission to {denied_action} grammar tables for this language."
            )));
        }
        Ok(())
    }

    async fn load_scope(&self, mut table: GrammarTable) -> AppResult<GrammarTable> {
        table.word_class_ids = sqlx::query_scalar("select word_class_id from grammar_table_word_classes where grammar_table_id = $1 order by word_class_id")
            .bind(table.id).fetch_all(&self.state.pool).await?;
        table.category_ids = sqlx::query_scalar("select category_id from grammar_table_categories where grammar_table_id = $1 order by category_id")
            .bind(table.id).fetch_all(&self.state.pool).await?;
        Ok(table)
    }

    async fn ensure_not_banned(&self, requestor: &User) -> AppResult<()> {
        UserBanRepository::new(self.state.clone())
            .ensure_not_banned(requestor.id)
            .await
    }

    async fn replace_scope(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        id: Uuid,
        classes: &[Uuid],
        categories: &[Uuid],
    ) -> AppResult<()> {
        sqlx::query("delete from grammar_table_word_classes where grammar_table_id = $1")
            .bind(id)
            .execute(&mut **tx)
            .await?;
        sqlx::query("delete from grammar_table_categories where grammar_table_id = $1")
            .bind(id)
            .execute(&mut **tx)
            .await?;
        for class in classes {
            sqlx::query("insert into grammar_table_word_classes (grammar_table_id, word_class_id) values ($1, $2)").bind(id).bind(class).execute(&mut **tx).await?;
        }
        for category in categories {
            sqlx::query("insert into grammar_table_categories (grammar_table_id, category_id) values ($1, $2)").bind(id).bind(category).execute(&mut **tx).await?;
        }
        Ok(())
    }

    pub async fn create(
        &self,
        requestor: &User,
        request: CreateGrammarTable,
    ) -> AppResult<GrammarTable> {
        request.body.validate(&request.preamble)?;
        self.validate_scope(
            request.language_id,
            &request.word_class_ids,
            &request.category_ids,
        )
        .await?;
        self.ensure_not_banned(requestor).await?;
        let mut tx = self.state.pool.begin().await?;
        let table = sqlx::query_as::<_, GrammarTable>("insert into grammar_tables (language_id, name, description, preamble, body, position, created_by, updated_by) values ($1, $2, $3, $4, $5, coalesce((select max(position) from grammar_tables where language_id = $1), -1) + 1, $6, $6) returning *")
            .bind(request.language_id).bind(request.name).bind(request.description).bind(request.preamble).bind(serde_json::to_value(&request.body)?).bind(requestor.id).fetch_one(&mut *tx).await?;
        self.replace_scope(
            &mut tx,
            table.id,
            &request.word_class_ids,
            &request.category_ids,
        )
        .await?;
        self.check_editor_with_audit(
            requestor,
            table.language_id,
            crate::model::audit_log::AuditActionType::Created,
            table.id,
            serde_json::json!({ "name": &table.name }),
            "create",
            &mut tx,
        )
        .await?;
        tx.commit().await?;
        self.load_scope(table).await
    }

    pub async fn get(&self, language: &Language, id: Uuid) -> AppResult<GrammarTable> {
        let table = sqlx::query_as::<_, GrammarTable>(
            "select * from grammar_tables where id = $1 and language_id = $2",
        )
        .bind(id)
        .bind(language.id)
        .fetch_one(&self.state.pool)
        .await?;
        self.load_scope(table).await
    }

    /// Finds a grammar table regardless of language. This is primarily used to
    /// resolve audit-log resources after an administrative action.
    pub async fn find_by_id(&self, id: Uuid) -> AppResult<GrammarTable> {
        let table = sqlx::query_as::<_, GrammarTable>("select * from grammar_tables where id = $1")
            .bind(id)
            .fetch_one(&self.state.pool)
            .await?;
        self.load_scope(table).await
    }

    pub async fn list(&self, language: &Language) -> AppResult<Vec<GrammarTable>> {
        let tables = sqlx::query_as::<_, GrammarTable>(
            "select * from grammar_tables where language_id = $1 order by position, id",
        )
        .bind(language.id)
        .fetch_all(&self.state.pool)
        .await?;
        let mut result = Vec::with_capacity(tables.len());
        for table in tables {
            result.push(self.load_scope(table).await?);
        }
        Ok(result)
    }

    pub async fn update(
        &self,
        requestor: &User,
        id: Uuid,
        request: UpdateGrammarTable,
    ) -> AppResult<GrammarTable> {
        request.body.validate(&request.preamble)?;
        let old: GrammarTable = sqlx::query_as("select * from grammar_tables where id = $1")
            .bind(id)
            .fetch_one(&self.state.pool)
            .await?;
        self.validate_scope(
            old.language_id,
            &request.word_class_ids,
            &request.category_ids,
        )
        .await?;
        self.ensure_not_banned(requestor).await?;
        let mut tx = self.state.pool.begin().await?;
        let table = sqlx::query_as::<_, GrammarTable>("update grammar_tables set name = $1, description = $2, preamble = $3, body = $4, schema_version = schema_version + 1, updated_by = $5, updated_at = now() where id = $6 returning *")
            .bind(request.name).bind(request.description).bind(request.preamble).bind(serde_json::to_value(&request.body)?).bind(requestor.id).bind(id).fetch_one(&mut *tx).await?;
        self.replace_scope(&mut tx, id, &request.word_class_ids, &request.category_ids)
            .await?;
        self.check_editor_with_audit(
            requestor,
            old.language_id,
            crate::model::audit_log::AuditActionType::Updated,
            id,
            serde_json::json!({ "name": &table.name }),
            "edit",
            &mut tx,
        )
        .await?;
        tx.commit().await?;
        self.load_scope(table).await
    }

    pub async fn delete(&self, requestor: &User, id: Uuid) -> AppResult<()> {
        let table: GrammarTable = sqlx::query_as("select * from grammar_tables where id = $1")
            .bind(id)
            .fetch_one(&self.state.pool)
            .await?;
        self.ensure_not_banned(requestor).await?;
        let mut tx = self.state.pool.begin().await?;
        self.check_editor_with_audit(
            requestor,
            table.language_id,
            crate::model::audit_log::AuditActionType::Deleted,
            table.id,
            serde_json::json!({ "name": &table.name }),
            "delete",
            &mut tx,
        )
        .await?;
        sqlx::query("delete from grammar_tables where id = $1")
            .bind(id)
            .execute(&mut *tx)
            .await?;
        sqlx::query("update grammar_tables set position = position - 1 where language_id = $1 and position > $2").bind(table.language_id).bind(table.position).execute(&mut *tx).await?;
        tx.commit().await?;
        Ok(())
    }

    pub async fn swap(
        &self,
        requestor: &User,
        language_id: Uuid,
        id1: Uuid,
        id2: Uuid,
    ) -> AppResult<()> {
        if id1 == id2 {
            return Err(bad_request(
                "Choose two different grammar tables to reorder.",
            ));
        }
        self.ensure_not_banned(requestor).await?;

        let mut tx = self.state.pool.begin().await?;
        let table1 = sqlx::query_as::<_, GrammarTable>(
            "select * from grammar_tables where id = $1 and language_id = $2",
        )
        .bind(id1)
        .bind(language_id)
        .fetch_one(&mut *tx)
        .await?;
        let table2 = sqlx::query_as::<_, GrammarTable>(
            "select * from grammar_tables where id = $1 and language_id = $2",
        )
        .bind(id2)
        .bind(language_id)
        .fetch_one(&mut *tx)
        .await?;

        self.check_editor_with_audit(
            requestor,
            language_id,
            crate::model::audit_log::AuditActionType::Updated,
            table1.id,
            serde_json::json!({
                "name": &table1.name,
                "action": "reordered",
                "swapped_with": table2.id,
            }),
            "reorder",
            &mut tx,
        )
        .await?;
        sqlx::query("update grammar_tables set position = $1, updated_by = $2, updated_at = now() where id = $3")
            .bind(table2.position)
            .bind(requestor.id)
            .bind(table1.id)
            .execute(&mut *tx)
            .await?;
        sqlx::query("update grammar_tables set position = $1, updated_by = $2, updated_at = now() where id = $3")
            .bind(table1.position)
            .bind(requestor.id)
            .bind(table2.id)
            .execute(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(())
    }

    pub async fn matching_for_word(&self, word: &Word) -> AppResult<Vec<GrammarTable>> {
        let Some(word_class) = word.word_class else {
            return Ok(Vec::new());
        };
        let tables = sqlx::query_as::<_, GrammarTable>(r#"
            select gt.* from grammar_tables gt
            where gt.language_id = $1
              and exists (select 1 from grammar_table_word_classes gtwc where gtwc.grammar_table_id = gt.id and gtwc.word_class_id = $2)
              and not exists (
                select 1 from grammar_table_categories gtc
                where gtc.grammar_table_id = gt.id
                  and not exists (select 1 from word_word_categories wwc where wwc.word = $3 and wwc.category = gtc.category_id)
              )
            order by gt.position, gt.id
        "#).bind(word.language).bind(word_class).bind(word.id).fetch_all(&self.state.pool).await?;
        let mut result = Vec::with_capacity(tables.len());
        for table in tables {
            result.push(self.load_scope(table).await?);
        }
        Ok(result)
    }

    pub async fn matching_table_for_word(
        &self,
        word: &Word,
        id: Uuid,
    ) -> AppResult<Option<GrammarTable>> {
        Ok(self
            .matching_for_word(word)
            .await?
            .into_iter()
            .find(|table| table.id == id))
    }

    /// Select one word to use as a representative preview for this table.
    /// The scope predicate is intentionally the inverse of `matching_for_word`
    /// so a preview can never be generated from an ineligible word.
    pub async fn random_example(
        &self,
        table: &GrammarTable,
    ) -> AppResult<Option<GrammarTableExample>> {
        let row = sqlx::query(
            r#"
                SELECT
                    words.id,
                    words.language,
                    words.word_class,
                    words.cognacy,
                    words.word,
                    words.slug,
                    words.lemma,
                    words.ipa,
                    words.notes,
                    words.extra,
                    words.like_count,
                    words.created_at,
                    words.updated_at,
                    words.created_by AS _created_by,
                    words.updated_by AS _updated_by,
                    ''::text AS bookmark,
                    NULL::text AS language_code,
                    NULL::text AS language_name,
                    NULL::text AS word_class_abbreviation,
                    NULL::text AS created_by,
                    NULL::text AS updated_by,
                    (
                        SELECT definition
                        FROM definitions
                        WHERE word = words.id
                        ORDER BY position
                        LIMIT 1
                    ) AS first_definition
                FROM words
                WHERE words.language = $1
                  AND EXISTS (
                    SELECT 1
                    FROM grammar_table_word_classes gtwc
                    WHERE gtwc.grammar_table_id = $2
                      AND gtwc.word_class_id = words.word_class
                  )
                  AND NOT EXISTS (
                    SELECT 1
                    FROM grammar_table_categories gtc
                    WHERE gtc.grammar_table_id = $2
                      AND NOT EXISTS (
                        SELECT 1
                        FROM word_word_categories wwc
                        WHERE wwc.word = words.id
                          AND wwc.category = gtc.category_id
                      )
                  )
                ORDER BY random()
                LIMIT 1
            "#,
        )
        .bind(table.language_id)
        .bind(table.id)
        .fetch_optional(&self.state.pool)
        .await?;

        let Some(row) = row else {
            return Ok(None);
        };
        Ok(Some(GrammarTableExample {
            first_definition: row.try_get("first_definition")?,
            word: Word::from_row(&row)?,
        }))
    }

    /// Fetches fresh entries for one word/input kind in a single query.  A
    /// stale record is intentionally indistinguishable from a miss; the
    /// upsert below refreshes it even before the maintenance job runs.
    pub async fn cached_outputs(
        &self,
        keys: &[GrammarCacheKey],
        ttl_seconds: i64,
    ) -> AppResult<std::collections::HashMap<String, String>> {
        let Some(first) = keys.first() else {
            return Ok(Default::default());
        };
        let hashes: Vec<&str> = keys.iter().map(|key| key.changes_hash.as_str()).collect();
        let entries = sqlx::query_as::<_, GrammarCacheEntry>("select changes_hash, output_word from grammar_render_cache where runner_version = $1 and source_kind = $2 and input_word = $3 and changes_hash = any($4) and created_at >= now() - ($5 * interval '1 second')")
            .bind(first.runner_version).bind(&first.source_kind).bind(&first.input_word).bind(hashes).bind(ttl_seconds)
            .fetch_all(&self.state.pool).await?;
        Ok(entries
            .into_iter()
            .map(|entry| (entry.changes_hash, entry.output_word))
            .collect())
    }

    pub async fn store_cached_output(
        &self,
        key: &GrammarCacheKey,
        output_word: &str,
    ) -> AppResult<()> {
        sqlx::query("insert into grammar_render_cache (runner_version, source_kind, changes_hash, input_word, output_word) values ($1, $2, $3, $4, $5) on conflict (runner_version, source_kind, changes_hash, input_word) do update set output_word = excluded.output_word, created_at = current_timestamp")
            .bind(key.runner_version).bind(&key.source_kind).bind(&key.changes_hash).bind(&key.input_word).bind(output_word)
            .execute(&self.state.pool).await?;
        Ok(())
    }
}

crate::util::repo_from_parts!(GrammarTableRepository);

#[cfg(test)]
mod tests {
    use super::*;

    fn body(cell: GrammarCell) -> GrammarBody {
        GrammarBody {
            columns: vec![GrammarColumn::Individual {
                heading: "number".into(),
                autogenerated: false,
            }],
            rows: vec![GrammarRow::Individual {
                heading: "singular".into(),
                autogenerated: false,
                cells: vec![cell],
            }],
        }
    }

    #[test]
    fn blank_program_is_valid_and_identity_is_empty() {
        let cell = GrammarCell::default();
        assert_eq!(cell.rowspan, 1);
        assert_eq!(cell.colspan, 1);
        assert!(body(cell).validate("").is_ok());
        assert_eq!(compose_changes("", ""), "");
        assert_eq!(compose_changes("a > e", ""), "a > e");
    }

    #[test]
    fn duplicate_word_class_ids_are_rejected_before_database_inserts() {
        let id = Uuid::new_v4();
        let error = ensure_unique_ids(&[id, id], "word class").unwrap_err();
        assert_eq!(error.status_code, axum::http::StatusCode::BAD_REQUEST);
        assert!(error.message.contains("same word class"));
    }

    #[test]
    fn duplicate_category_ids_are_rejected_before_database_inserts() {
        let id = Uuid::new_v4();
        let error = ensure_unique_ids(&[id, id], "category").unwrap_err();
        assert_eq!(error.status_code, axum::http::StatusCode::BAD_REQUEST);
        assert!(error.message.contains("same category"));
    }

    #[test]
    fn a_covered_cell_cannot_contain_rules() {
        let mut grid = GrammarBody {
            columns: vec![
                GrammarColumn::Individual {
                    heading: "a".into(),
                    autogenerated: false,
                },
                GrammarColumn::Individual {
                    heading: "b".into(),
                    autogenerated: false,
                },
            ],
            rows: vec![GrammarRow::Individual {
                heading: "r".into(),
                autogenerated: false,
                cells: vec![
                    GrammarCell {
                        changes: "a > e".into(),
                        rowspan: 1,
                        colspan: 2,
                    },
                    GrammarCell {
                        changes: "x > y".into(),
                        ..Default::default()
                    },
                ],
            }],
        };
        assert!(grid.validate("").is_err());
        if let GrammarRow::Individual { cells, .. } = &mut grid.rows[0] {
            cells[1].changes.clear();
        }
        assert!(grid.validate("").is_ok());
    }
}
