use crate::AppState;
use crate::err::{AppResult, bad_request, forbidden};
use askama::filters::{Html, escape};
use crate::model::language_invites::PermissionLevel;
use crate::model::language_permissions::LanguagePermissionRepository;
use crate::model::languages::Language;
use crate::model::user_bans::UserBanRepository;
use crate::model::users::User;
use crate::pagination::{PaginatedRequest, PaginatedResponse};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::FromRow;
use std::collections::VecDeque;
use std::fmt::Write;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Phoneme {
    pub text: String,
    pub annotations: Vec<u32>,
}

fn span_default() -> u32 {
    1
}

fn span_is_default(span: &u32) -> bool {
    *span == 1
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Cell {
    pub phonemes: Vec<Phoneme>,
    #[serde(default = "span_default", skip_serializing_if = "span_is_default")]
    pub rowspan: u32,
    #[serde(default = "span_default", skip_serializing_if = "span_is_default")]
    pub colspan: u32,
}

impl Default for Cell {
    fn default() -> Self {
        Self {
            phonemes: vec![],
            rowspan: 1,
            colspan: 1,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Row {
    Group {
        heading: String,
        #[serde(default)]
        autogenerated: bool,
        rows: Vec<Row>,
    },
    Individual {
        heading: String,
        #[serde(default)]
        autogenerated: bool,
        cells: Vec<Cell>,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Column {
    Group {
        heading: String,
        #[serde(default)]
        autogenerated: bool,
        columns: Vec<Column>,
    },
    Individual {
        heading: String,
        #[serde(default)]
        autogenerated: bool,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Body {
    pub rows: Vec<Row>,
    pub columns: Vec<Column>,
    pub annotations: Vec<String>,
}

impl Body {
    pub fn validate(&self) -> AppResult<()> {
        // invariants:
        // - all rows must have the same number of cells
        // - the number of cells in each row must match the number of individual columns
        // - all phonemes must be non-empty strings
        // - all references to annotations must be valid indices into the annotations array
        // - rowspan/colspan must be >= 1, merged regions must fit in the grid and
        //   not overlap, and cells hidden under a merged region must be empty

        fn count_individual_columns(columns: &[Column]) -> usize {
            let mut count = 0;
            for column in columns {
                match column {
                    Column::Group { columns, .. } => {
                        count += count_individual_columns(columns);
                    }
                    Column::Individual { .. } => {
                        count += 1;
                    }
                }
            }
            count
        }

        fn validate_num_cells_in_rows(rows: &[Row], num_columns: usize) -> AppResult<()> {
            for row in rows {
                match row {
                    Row::Group { rows, .. } => {
                        validate_num_cells_in_rows(rows, num_columns)?;
                    }
                    Row::Individual { cells, .. } => {
                        if cells.len() != num_columns {
                            return Err(bad_request(format!(
                                "Each row must have the same number of cells as there are individual columns. Expected {}, found {}.",
                                num_columns,
                                cells.len()
                            )));
                        }
                    }
                }
            }
            Ok(())
        }

        fn validate_phonemes_in_rows(rows: &[Row], annotations_len: usize) -> AppResult<()> {
            for row in rows {
                match row {
                    Row::Group { rows, .. } => {
                        validate_phonemes_in_rows(rows, annotations_len)?;
                    }
                    Row::Individual { cells, .. } => {
                        for cell in cells {
                            for phoneme in &cell.phonemes {
                                if phoneme.text.trim().is_empty() {
                                    return Err(bad_request(
                                        "Phoneme strings cannot be empty.".to_owned(),
                                    ));
                                }
                                for &annotation_index in &phoneme.annotations {
                                    if annotation_index as usize >= annotations_len {
                                        return Err(bad_request(format!(
                                            "Annotation index {} is out of bounds.",
                                            annotation_index
                                        )));
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Ok(())
        }

        fn collect_leaf_cells<'a>(rows: &'a [Row], out: &mut Vec<&'a [Cell]>) {
            for row in rows {
                match row {
                    Row::Group { rows, .. } => collect_leaf_cells(rows, out),
                    Row::Individual { cells, .. } => out.push(cells),
                }
            }
        }

        fn validate_spans(rows: &[Row], num_columns: usize) -> AppResult<()> {
            let mut leaf_rows = Vec::new();
            collect_leaf_cells(rows, &mut leaf_rows);
            let num_rows = leaf_rows.len();

            // row-major sweep; each merged region claims its covered cells, and any
            // cell we reach that's already claimed must be an empty 1x1 cell
            let mut occupied = vec![vec![false; num_columns]; num_rows];
            for (r, cells) in leaf_rows.iter().enumerate() {
                for (c, cell) in cells.iter().enumerate() {
                    if cell.rowspan < 1 || cell.colspan < 1 {
                        return Err(bad_request(
                            "Cell rowspan and colspan must be at least 1.".to_owned(),
                        ));
                    }
                    if occupied[r][c] {
                        if !cell.phonemes.is_empty() {
                            return Err(bad_request(
                                "Cells covered by a merged cell must be empty.".to_owned(),
                            ));
                        }
                        if cell.rowspan != 1 || cell.colspan != 1 {
                            return Err(bad_request(
                                "Merged cells cannot overlap each other.".to_owned(),
                            ));
                        }
                        continue;
                    }
                    let rowspan = cell.rowspan as usize;
                    let colspan = cell.colspan as usize;
                    if r + rowspan > num_rows || c + colspan > num_columns {
                        return Err(bad_request(
                            "Merged cells cannot extend past the edge of the table.".to_owned(),
                        ));
                    }
                    for row_slots in occupied.iter_mut().skip(r).take(rowspan) {
                        for slot in row_slots.iter_mut().skip(c).take(colspan) {
                            if *slot {
                                return Err(bad_request(
                                    "Merged cells cannot overlap each other.".to_owned(),
                                ));
                            }
                            *slot = true;
                        }
                    }
                }
            }
            Ok(())
        }

        let num_columns = count_individual_columns(&self.columns);
        validate_num_cells_in_rows(&self.rows, num_columns)?;
        validate_phonemes_in_rows(&self.rows, self.annotations.len())?;
        validate_spans(&self.rows, num_columns)?;

        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct PhonologyTable {
    pub id: Uuid,
    #[serde(skip_serializing)]
    pub language_id: Uuid,
    pub name: String,
    pub description: String,
    pub position: i32,

    pub body: Value,
    pub schema_version: i32,

    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Column {
    fn count_leaves(&self) -> usize {
        match self {
            Column::Individual { .. } => 1,
            Column::Group { columns, .. } => columns.iter().map(|c| c.count_leaves()).sum(),
        }
    }

    fn max_depth(columns: &[Column], depth: usize) -> usize {
        let mut max = depth;
        for col in columns {
            if let Column::Group { columns, .. } = col {
                max = max.max(Column::max_depth(columns, depth + 1));
            }
        }
        max
    }
}

struct HeaderCell {
    heading: String,
    colspan: usize,
    rowspan: usize,
}

pub struct TableRenderOptions {
    pub standalone_link: Option<String>,
    pub edit_links: Option<(String, String, String)>, // (edit meta, edit body, delete)
    pub header_el: String,
}

// html-escape any user-controlled string before writing it into the output.
// the renderer concatenates raw html, so every dynamic value (headings, phoneme
// text, table name, annotation text, links built from language codes) has to go
// through this — otherwise a phoneme like `<script>` is xss.
fn esc(s: &str) -> impl std::fmt::Display + '_ {
    escape(s, Html).unwrap()
}

impl PhonologyTable {
    pub fn to_html(&self, options: &TableRenderOptions) -> AppResult<String> {
        fn max_row_group_depth(rows: &[Row], current_depth: usize) -> usize {
            let mut max_depth = current_depth;
            for row in rows {
                if let Row::Group { rows, .. } = row {
                    let depth = max_row_group_depth(rows, current_depth + 1);
                    if depth > max_depth {
                        max_depth = depth;
                    }
                }
            }
            max_depth
        }

        fn count_individual_rows(rows: &[Row]) -> usize {
            let mut count = 0;
            for row in rows {
                match row {
                    Row::Group { rows, .. } => count += count_individual_rows(rows),
                    Row::Individual { .. } => count += 1,
                }
            }
            count
        }

        // positions (leaf row index, column index) hidden underneath a merged cell;
        // these are skipped when emitting <td>s
        fn compute_covered_cells(rows: &[Row]) -> std::collections::HashSet<(usize, usize)> {
            fn collect_leaf_cells<'a>(rows: &'a [Row], out: &mut Vec<&'a [Cell]>) {
                for row in rows {
                    match row {
                        Row::Group { rows, .. } => collect_leaf_cells(rows, out),
                        Row::Individual { cells, .. } => out.push(cells),
                    }
                }
            }
            let mut leaf_rows = Vec::new();
            collect_leaf_cells(rows, &mut leaf_rows);
            let mut covered = std::collections::HashSet::new();
            for (r, cells) in leaf_rows.iter().enumerate() {
                for (c, cell) in cells.iter().enumerate() {
                    if covered.contains(&(r, c)) {
                        continue;
                    }
                    for dr in 0..cell.rowspan as usize {
                        for dc in 0..cell.colspan as usize {
                            if (dr, dc) != (0, 0) {
                                covered.insert((r + dr, c + dc));
                            }
                        }
                    }
                }
            }
            covered
        }

        // pending_groups: group headings from ancestor Row::Groups that haven't been
        // emitted yet — they get attached to the first <tr> they contain
        fn write_rows(
            html: &mut String,
            rows: &[Row],
            pending_groups: &mut Vec<(String, usize)>, // (heading, rowspan)
            max_row_group_depth: usize,
            current_depth: usize,
            leaf_row: &mut usize,
            covered: &std::collections::HashSet<(usize, usize)>,
        ) {
            for row in rows {
                match row {
                    Row::Group { heading, rows, .. } => {
                        let rowspan = count_individual_rows(rows);
                        pending_groups.push((heading.clone(), rowspan));
                        write_rows(
                            html,
                            rows,
                            pending_groups,
                            max_row_group_depth,
                            current_depth + 1,
                            leaf_row,
                            covered,
                        );
                    }
                    Row::Individual { heading, cells, .. } => {
                        html.push_str("<tr>");

                        // emit any pending group headers (they attach to this first row)
                        for (group_heading, rowspan) in pending_groups.drain(..) {
                            write!(html, "<th").unwrap();
                            if rowspan > 1 {
                                write!(html, " rowspan=\"{rowspan}\"").unwrap();
                            }
                            write!(html, ">{}</th>", esc(&group_heading)).unwrap();
                        }

                        // individual row heading — colspan to fill remaining group columns
                        let colspan = max_row_group_depth - current_depth;
                        write!(html, "<th").unwrap();
                        if colspan > 1 {
                            write!(html, " colspan=\"{colspan}\"").unwrap();
                        }
                        write!(html, ">{}</th>", esc(heading)).unwrap();

                        for (ci, cell) in cells.iter().enumerate() {
                            if covered.contains(&(*leaf_row, ci)) {
                                continue;
                            }
                            html.push_str("<td");
                            if cell.rowspan > 1 {
                                write!(html, " rowspan=\"{}\"", cell.rowspan).unwrap();
                            }
                            if cell.colspan > 1 {
                                write!(html, " colspan=\"{}\"", cell.colspan).unwrap();
                            }
                            html.push('>');
                            for (i, phoneme) in cell.phonemes.iter().enumerate() {
                                if i > 0 {
                                    html.push_str(", ");
                                }
                                html.push_str("<span class=\"phoneme\">");
                                write!(html, "{}", esc(&phoneme.text)).unwrap();
                                html.push_str("</span>");
                                for &annotation_index in &phoneme.annotations {
                                    let annotation_index = annotation_index + 1; // 1-based for display
                                    write!(html, "<sup><a href=\"#annotation-{annotation_index}\" class=\"annotation\">{annotation_index}</a></sup>").unwrap();
                                }
                            }
                            html.push_str("</td>");
                        }
                        html.push_str("</tr>");
                        *leaf_row += 1;
                    }
                }
            }
        }

        let mut html = String::new();
        let body: Body = serde_json::from_value(self.body.clone())?;

        html.push_str("<div class=\"phonology-table-container\">");

        html.push_str("<div class=\"header-with-actions\">");
        write!(
            html,
            "<{} id=\"table-{}\">{}</{}>",
            options.header_el,
            self.id,
            esc(&self.name),
            options.header_el
        )?;
        html.push_str("<ul>");
        if let Some(standalone_link) = &options.standalone_link {
            write!(
                html,
                "<li><a class=\"with-icon\" href=\"{}\">",
                esc(standalone_link)
            )
            .unwrap();
            html.push_str(r#"
                    <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><!-- Icon from Material Symbols by Google - https://github.com/google/material-design-icons/blob/master/LICENSE --><path fill="currentColor" d="M9 18h11v-2.675H9zM4 8.675h3V6H4zm0 4.675h3v-2.675H4zM4 18h3v-2.675H4zm5-4.65h11v-2.675H9zm0-4.675h11V6H9zM4 20q-.825 0-1.412-.587T2 18V6q0-.825.588-1.412T4 4h16q.825 0 1.413.588T22 6v12q0 .825-.587 1.413T20 20z"/></svg>
                    <span>view table</span></a></li>"#);
        };
        if let Some((edit_meta_link, edit_body_link, delete_link)) = &options.edit_links {
            write!(
                html,
                "<li><a class=\"with-icon\" href=\"{}\">",
                esc(edit_meta_link)
            )
            .unwrap();
            html.push_str(r#"
                    <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><!-- Icon from Material Symbols by Google - https://github.com/google/material-design-icons/blob/master/LICENSE --><path fill="currentColor" d="M5 21q-.825 0-1.412-.587T3 19V5q0-.825.588-1.412T5 3h14q.825 0 1.413.588T21 5v14q0 .825-.587 1.413T19 21zm0-2h14V5H5zM7 9h10v2H7zm0 4h7v2H7z"/></svg>
                <span>edit table metadata</span></a></li>"#);
            write!(
                html,
                "<li><a class=\"with-icon\" href=\"{}\">",
                esc(edit_body_link)
            )
            .unwrap();
            html.push_str(r#"
                    <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><!-- Icon from Material Symbols by Google - https://github.com/google/material-design-icons/blob/master/LICENSE --><path fill="currentColor" d="M5 21q-.825 0-1.412-.587T3 19V5q0-.825.588-1.412T5 3h14q.825 0 1.413.588T21 5v14q0 .825-.587 1.413T19 21zm0-2h14V5H5zM7 9h10v2H7zm0 4h7v2H7z"/></svg>
                <span>edit table body</span></a></li>"#);

            write!(
                html,
                "<li><a class=\"with-icon\" href=\"{}\">",
                esc(delete_link)
            )
            .unwrap();
            html.push_str(r#"
                <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><!-- Icon from Material Symbols by Google - https://github.com/google/material-design-icons/blob/master/LICENSE --><path fill="currentColor" d="M7 21q-.825 0-1.412-.587T5 19V6H4V4h5V3h6v1h5v2h-1v13q0 .825-.587 1.413T17 21zM17 6H7v13h10zM9 17h2V8H9zm4 0h2V8h-2zM7 6v13z"/></svg>
                <span>delete table</span></a></li>"#);
        }
        html.push_str("</ul></div>");

        html.push_str("<div class=\"phonology-table-scroll\">");

        write!(
            html,
            "<table class=\"phonology-table\" aria-labelledby=\"table-{}\">",
            self.id
        )?;

        // --- thead: column headers ---
        let max_col_depth = Column::max_depth(&body.columns, 1);
        let max_row_depth = max_row_group_depth(&body.rows, 1);

        // BFS to build header rows
        let mut header_rows: Vec<Vec<HeaderCell>> =
            (0..max_col_depth).map(|_| Vec::new()).collect();
        let mut queue: VecDeque<(&Column, usize)> = body.columns.iter().map(|c| (c, 0)).collect();

        while let Some((col, depth)) = queue.pop_front() {
            match col {
                Column::Group {
                    heading, columns, ..
                } => {
                    header_rows[depth].push(HeaderCell {
                        heading: heading.clone(),
                        colspan: col.count_leaves(),
                        rowspan: 1,
                    });
                    for child in columns {
                        queue.push_back((child, depth + 1));
                    }
                }
                Column::Individual { heading, .. } => {
                    header_rows[depth].push(HeaderCell {
                        heading: heading.clone(),
                        colspan: 1,
                        rowspan: max_col_depth - depth,
                    });
                }
            }
        }

        html.push_str("<thead>");
        for (i, row) in header_rows.iter().enumerate() {
            html.push_str("<tr>");
            // first header row gets an empty corner cell spanning all row-header columns
            if i == 0 {
                write!(
                    &mut html,
                    "<th colspan=\"{max_row_depth}\" rowspan=\"{max_col_depth}\"></th>"
                )
                .unwrap();
            }
            for cell in row {
                write!(&mut html, "<th").unwrap();
                if cell.colspan > 1 {
                    write!(&mut html, " colspan=\"{}\"", cell.colspan).unwrap();
                }
                if cell.rowspan > 1 {
                    write!(&mut html, " rowspan=\"{}\"", cell.rowspan).unwrap();
                }
                write!(&mut html, ">{}</th>", esc(&cell.heading)).unwrap();
            }
            html.push_str("</tr>");
        }
        html.push_str("</thead>");

        // --- tbody: data rows ---
        html.push_str("<tbody>");
        let mut pending_groups: Vec<(String, usize)> = Vec::new();
        let covered = compute_covered_cells(&body.rows);
        let mut leaf_row = 0;
        write_rows(
            &mut html,
            &body.rows,
            &mut pending_groups,
            max_row_depth + 1,
            1,
            &mut leaf_row,
            &covered,
        );
        html.push_str("</tbody>");

        html.push_str("</table>");
        html.push_str("</div>");

        html.push_str("<ol class=\"annotations\">");
        for (i, annotation) in body.annotations.iter().enumerate() {
            let i = i + 1;
            write!(html, "<li id=\"annotation-{i}\">{}</li>", esc(annotation)).unwrap();
        }
        html.push_str("</ol>");
        html.push_str("</div>");
        Ok(html)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct CreatePhonologyTable {
    pub language_id: Uuid,
    pub name: String,
    pub description: Option<String>,

    pub body: Body,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct UpdatePhonologyTable {
    pub name: Option<String>,
    pub description: Option<String>,

    pub body: Option<Body>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchPhonologyTable {
    pub q: Option<String>,
    #[serde(
        default,
        deserialize_with = "crate::util::deserialize_optional_form_datetime"
    )]
    pub created_before: Option<DateTime<Utc>>,
    #[serde(
        default,
        deserialize_with = "crate::util::deserialize_optional_form_datetime"
    )]
    pub created_after: Option<DateTime<Utc>>,
}

crate::util::text_query!(SearchPhonologyTable);

pub struct PhonologyTableRepository {
    state: AppState,
}

impl PhonologyTableRepository {
    pub fn new(state: AppState) -> Self {
        Self { state }
    }

    pub async fn create(
        &self,
        requestor: &User,
        req: CreatePhonologyTable,
    ) -> AppResult<PhonologyTable> {
        UserBanRepository::new(self.state.clone())
            .ensure_not_banned(requestor.id)
            .await?;
        req.body.validate()?;

        let can_edit = LanguagePermissionRepository::new(self.state.clone())
            .has_permission(requestor.id, req.language_id, PermissionLevel::Editor)
            .await?;

        if !can_edit {
            return Err(forbidden(
                "You do not have permission to create phonology tables for this language.",
            ));
        }

        let result = sqlx::query_as!(
            PhonologyTable,
            r#"
            insert into phonology_tables (language_id, name, description, body, position, schema_version)
            values ($1, $2, $3, $4,
            COALESCE((SELECT MAX(position) FROM phonology_tables WHERE language_id = $1), -1) + 1,
            1)
            returning *
            "#,
            req.language_id,
            req.name,
            req.description.unwrap_or_default(),
            serde_json::to_value(&req.body).unwrap(),
        )
        .fetch_one(&self.state.pool)
        .await?;

        Ok(result)
    }

    pub async fn swap(
        &self,
        requestor: &User,
        language_id: Uuid,
        id1: Uuid,
        id2: Uuid,
    ) -> AppResult<()> {
        UserBanRepository::new(self.state.clone())
            .ensure_not_banned(requestor.id)
            .await?;

        let can_edit = LanguagePermissionRepository::new(self.state.clone())
            .has_permission(requestor.id, language_id, PermissionLevel::Editor)
            .await?;

        if !can_edit {
            return Err(forbidden(
                "You do not have permission to reorder phonology tables for this language.",
            ));
        }

        let mut tx = self.state.pool.begin().await?;

        let table1 = sqlx::query_as!(
            PhonologyTable,
            "select * from phonology_tables where id = $1 and language_id = $2",
            id1,
            language_id
        )
        .fetch_one(&mut *tx)
        .await?;

        let table2 = sqlx::query_as!(
            PhonologyTable,
            "select * from phonology_tables where id = $1 and language_id = $2",
            id2,
            language_id
        )
        .fetch_one(&mut *tx)
        .await?;

        sqlx::query!(
            "update phonology_tables set position = $1 where id = $2",
            table2.position,
            table1.id
        )
        .execute(&mut *tx)
        .await?;

        sqlx::query!(
            "update phonology_tables set position = $1 where id = $2",
            table1.position,
            table2.id
        )
        .execute(&mut *tx)
        .await?;

        tx.commit().await?;

        Ok(())
    }

    pub async fn update(
        &self,
        requestor: &User,
        id: Uuid,
        req: UpdatePhonologyTable,
    ) -> AppResult<PhonologyTable> {
        UserBanRepository::new(self.state.clone())
            .ensure_not_banned(requestor.id)
            .await?;

        let existing = sqlx::query_as!(
            PhonologyTable,
            "select * from phonology_tables where id = $1",
            id
        )
        .fetch_one(&self.state.pool)
        .await?;

        let can_edit = LanguagePermissionRepository::new(self.state.clone())
            .has_permission(requestor.id, existing.language_id, PermissionLevel::Editor)
            .await?;

        if !can_edit {
            return Err(forbidden(
                "You do not have permission to edit phonology tables for this language.",
            ));
        }

        if let Some(body) = &req.body {
            body.validate()?;
        }

        let updated = sqlx::query_as!(
            PhonologyTable,
            r#"
            update phonology_tables
            set name = COALESCE($1, name),
                description = COALESCE($2, description),
                body = COALESCE($3, body),
                schema_version = CASE WHEN $3 IS NOT NULL THEN schema_version + 1 ELSE schema_version END,
                updated_at = now()
            where id = $4
            returning *
            "#,
            req.name,
            req.description,
            req.body.as_ref().map(|b| serde_json::to_value(b).unwrap()),
            id
        )
        .fetch_one(&self.state.pool)
        .await?;

        Ok(updated)
    }

    pub async fn delete(&self, requestor: &User, id: Uuid) -> AppResult<()> {
        UserBanRepository::new(self.state.clone())
            .ensure_not_banned(requestor.id)
            .await?;

        let existing = sqlx::query_as!(
            PhonologyTable,
            "select * from phonology_tables where id = $1",
            id
        )
        .fetch_one(&self.state.pool)
        .await?;

        let can_edit = LanguagePermissionRepository::new(self.state.clone())
            .has_permission(requestor.id, existing.language_id, PermissionLevel::Editor)
            .await?;

        if !can_edit {
            return Err(forbidden(
                "You do not have permission to delete phonology tables for this language.",
            ));
        }

        let mut tx = self.state.pool.begin().await?;

        sqlx::query!("delete from phonology_tables where id = $1", id)
            .execute(&mut *tx)
            .await?;

        // decrement position of all tables with greater position

        sqlx::query!(
            "update phonology_tables set position = position - 1 where language_id = $1 and position > $2",
            existing.language_id,
            existing.position
        )
        .execute(&mut *tx)
        .await?;

        tx.commit().await?;

        Ok(())
    }

    pub async fn get(&self, language: &Language, id: Uuid) -> AppResult<PhonologyTable> {
        let table = sqlx::query_as!(
            PhonologyTable,
            "select * from phonology_tables where id = $1 and language_id = $2",
            id,
            language.id
        )
        .fetch_one(&self.state.pool)
        .await?;

        Ok(table)
    }

    pub async fn search(
        &self,
        language: &Language,
        pagination: PaginatedRequest,
        search: SearchPhonologyTable,
    ) -> AppResult<PaginatedResponse<PhonologyTable>> {
        let items_future = sqlx::query_as!(
            PhonologyTable,
            r#"
                SELECT pt.*
                FROM phonology_tables pt
                WHERE
                pt.language_id = $1
                AND ($5::TEXT IS NULL OR pt.created_at >= $5::TEXT::timestamptz)
                AND ($6::TEXT IS NULL OR pt.created_at <= $6::TEXT::timestamptz)
                ORDER BY (
                    CASE
                        WHEN $2::TEXT IS NOT NULL AND pt.name ILIKE '%' || $2 || '%' THEN 100.0
                        WHEN $2::TEXT IS NOT NULL AND pt.description ILIKE '%' || $2 || '%' THEN 80.0
                        ELSE 0.0
                    END +
                    CASE WHEN $2::TEXT IS NOT NULL THEN
                        similarity(pt.name, $2) * 3.0 +
                        COALESCE(similarity(pt.description, $2), 0.0) * 1.0
                    ELSE 0.0
                    END
                ) DESC, pt.position ASC, pt.id DESC
                LIMIT $3
                OFFSET $4
            "#,
            language.id,
            search.q,
            i64::from(pagination.limit),
            i64::from(pagination.offset),
            search.created_after.map(|d| d.to_rfc3339()),
            search.created_before.map(|d| d.to_rfc3339()),
        )
        .fetch_all(&self.state.pool);

        let count_future = sqlx::query_scalar!(
            r#"
                SELECT COUNT(*)
                FROM phonology_tables pt
                WHERE pt.language_id = $1
                AND ($2::TEXT IS NULL OR pt.created_at >= $2::TEXT::timestamptz)
                AND ($3::TEXT IS NULL OR pt.created_at <= $3::TEXT::timestamptz)
            "#,
            language.id,
            search.created_after.map(|d| d.to_rfc3339()),
            search.created_before.map(|d| d.to_rfc3339()),
        )
        .fetch_one(&self.state.pool);

        let (items, total_count) = tokio::try_join!(items_future, count_future)?;

        let total = total_count.unwrap_or(0);
        let has_more =
            (i64::from(pagination.offset) + i64::try_from(items.len()).unwrap_or(i64::MAX)) < total;

        Ok(PaginatedResponse {
            items,
            total,
            offset: pagination.offset,
            limit: pagination.limit,
            has_more,
        })
    }
}

crate::util::repo_from_parts!(PhonologyTableRepository);

#[cfg(test)]
mod tests {
    use super::*;

    fn cell(texts: &[&str]) -> Cell {
        Cell {
            phonemes: texts
                .iter()
                .map(|t| Phoneme {
                    text: (*t).to_string(),
                    annotations: vec![],
                })
                .collect(),
            ..Default::default()
        }
    }

    fn spanned(texts: &[&str], rowspan: u32, colspan: u32) -> Cell {
        Cell {
            rowspan,
            colspan,
            ..cell(texts)
        }
    }

    fn individual_row(heading: &str, cells: Vec<Cell>) -> Row {
        Row::Individual {
            heading: heading.to_string(),
            autogenerated: false,
            cells,
        }
    }

    fn individual_column(heading: &str) -> Column {
        Column::Individual {
            heading: heading.to_string(),
            autogenerated: false,
        }
    }

    // 2x3 grid
    fn simple_body(rows: Vec<Row>) -> Body {
        Body {
            rows,
            columns: vec![
                individual_column("C1"),
                individual_column("C2"),
                individual_column("C3"),
            ],
            annotations: vec![],
        }
    }

    #[test]
    fn spans_default_to_one_when_absent_in_json() {
        let cell: Cell = serde_json::from_str(r#"{"phonemes": []}"#).unwrap();
        assert_eq!(cell.rowspan, 1);
        assert_eq!(cell.colspan, 1);
    }

    #[test]
    fn default_spans_are_not_serialized() {
        let json = serde_json::to_value(cell(&["a"])).unwrap();
        assert!(json.get("rowspan").is_none());
        assert!(json.get("colspan").is_none());
        let json = serde_json::to_value(spanned(&["a"], 2, 1)).unwrap();
        assert_eq!(json["rowspan"], 2);
        assert!(json.get("colspan").is_none());
    }

    #[test]
    fn validate_accepts_merged_region() {
        let body = simple_body(vec![
            individual_row(
                "R1",
                vec![spanned(&["a"], 2, 2), cell(&[]), cell(&["b"])],
            ),
            individual_row("R2", vec![cell(&[]), cell(&[]), cell(&["c"])]),
        ]);
        assert!(body.validate().is_ok());
    }

    #[test]
    fn validate_rejects_zero_span() {
        let body = simple_body(vec![individual_row(
            "R1",
            vec![spanned(&["a"], 0, 1), cell(&[]), cell(&[])],
        )]);
        assert!(body.validate().is_err());
    }

    #[test]
    fn validate_rejects_out_of_bounds_span() {
        let body = simple_body(vec![
            individual_row("R1", vec![cell(&[]), cell(&[]), spanned(&["a"], 1, 2)]),
            individual_row("R2", vec![cell(&[]), cell(&[]), cell(&[])]),
        ]);
        assert!(body.validate().is_err());

        let body = simple_body(vec![
            individual_row("R1", vec![cell(&[]), cell(&[]), cell(&[])]),
            individual_row("R2", vec![spanned(&["a"], 2, 1), cell(&[]), cell(&[])]),
        ]);
        assert!(body.validate().is_err());
    }

    #[test]
    fn validate_rejects_overlapping_spans() {
        // b is anchored at (0,1), which a's colspan already covers
        let body = simple_body(vec![individual_row(
            "R1",
            vec![spanned(&["a"], 1, 2), spanned(&["b"], 1, 2), cell(&[])],
        )]);
        assert!(body.validate().is_err());
    }

    #[test]
    fn validate_rejects_covered_cell_with_phonemes() {
        let body = simple_body(vec![individual_row(
            "R1",
            vec![spanned(&["a"], 1, 2), cell(&["hidden"]), cell(&[])],
        )]);
        assert!(body.validate().is_err());
    }

    #[test]
    fn validate_rejects_span_crossing_into_occupied_cell() {
        // rowspan from R1 collides with a colspan anchored in R2
        let body = simple_body(vec![
            individual_row("R1", vec![cell(&[]), spanned(&["a"], 2, 1), cell(&[])]),
            individual_row("R2", vec![spanned(&["b"], 1, 2), cell(&[]), cell(&[])]),
        ]);
        assert!(body.validate().is_err());
    }

    #[test]
    fn to_html_skips_covered_cells_and_emits_span_attrs() {
        let body = simple_body(vec![
            individual_row(
                "R1",
                vec![spanned(&["w"], 2, 2), cell(&[]), cell(&["k"])],
            ),
            individual_row("R2", vec![cell(&[]), cell(&[]), cell(&["g"])]),
        ]);
        body.validate().unwrap();
        let table = PhonologyTable {
            id: Uuid::nil(),
            language_id: Uuid::nil(),
            name: "test".to_string(),
            description: String::new(),
            position: 0,
            body: serde_json::to_value(&body).unwrap(),
            schema_version: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let html = table
            .to_html(&TableRenderOptions {
                standalone_link: None,
                edit_links: None,
                header_el: "h2".to_string(),
            })
            .unwrap();
        assert!(html.contains(r#"<td rowspan="2" colspan="2">"#));
        // 6 grid positions, 3 covered -> 3 <td>s
        assert_eq!(html.matches("<td").count(), 3);
    }

    #[test]
    fn validate_allows_span_crossing_row_group_boundary() {
        // spanning across a group boundary is allowed as long as it stays in bounds
        let body = simple_body(vec![
            individual_row("R1", vec![spanned(&["a"], 2, 1), cell(&[]), cell(&[])]),
            Row::Group {
                heading: "G".to_string(),
                autogenerated: false,
                rows: vec![individual_row(
                    "R2",
                    vec![cell(&[]), cell(&["b"]), cell(&[])],
                )],
            },
        ]);
        assert!(body.validate().is_ok());
    }
}
