// The shared, content-agnostic half of the table editor.  It knows about
// headings, selection, history and spans; callers provide the cell payload.
export type GridCell = { rowspan?: number; colspan?: number };
export type Row<C extends GridCell> =
  | { type: "Group"; heading: string; autogenerated?: boolean; rows: Row<C>[] }
  | {
      type: "Individual";
      heading: string;
      autogenerated?: boolean;
      cells: C[];
    };
export type Column =
  | {
      type: "Group";
      heading: string;
      autogenerated?: boolean;
      columns: Column[];
    }
  | { type: "Individual"; heading: string; autogenerated?: boolean };
export type Body<C extends GridCell> = { rows: Row<C>[]; columns: Column[] };
export type HeadingPath = number[];
export type Focus =
  | { type: "TopLeft" }
  | { type: "RowHeading"; path: HeadingPath }
  | { type: "ColumnHeading"; path: HeadingPath }
  | { type: "Cell"; row: number; column: number };
export type Movement =
  | "Up"
  | "Down"
  | "Left"
  | "Right"
  | "Tab"
  | "ShiftTab"
  | "Home"
  | "End";
export type Snapshot<C extends GridCell> = {
  body: Body<C>;
  focus: Focus;
  select: Focus | null;
};
export type State<C extends GridCell> = Snapshot<C> & {
  undoStack: Snapshot<C>[];
  redoStack: Snapshot<C>[];
};
export type Action<C extends GridCell> =
  | { type: "Focus"; focus: Focus }
  | { type: "Select"; select: Focus | null }
  | {
      type: "EditHeading";
      kind: "row" | "column";
      path: HeadingPath;
      heading: string;
    }
  | { type: "SetCell"; row: number; column: number; cell: C }
  | {
      type: "AddHeading";
      kind: "row" | "column";
      path: HeadingPath;
      position: "before" | "after";
    }
  | { type: "DeleteHeading"; kind: "row" | "column"; path: HeadingPath }
  | { type: "SplitHeading"; kind: "row" | "column"; path: HeadingPath }
  | {
      type: "Merge";
      first: { row: number; column: number };
      second: { row: number; column: number };
    }
  | { type: "Unmerge"; row: number; column: number }
  | { type: "Undo" }
  | { type: "Redo" };
export type Options<C extends GridCell> = {
  createCell: () => C;
  mergeCells: (anchor: C, covered: C[]) => C;
};

export const leaves = <T extends Row<any> | Column>(items: T[]): T[] =>
  items.flatMap((item) =>
    item.type === "Group"
      ? leaves(("rows" in item ? item.rows : item.columns) as T[])
      : [item],
  );
export const leafCount = <T extends Row<any> | Column>(items: T[]): number =>
  leaves(items).length;
export const headingAt = <T extends Row<any> | Column>(
  items: T[],
  path: HeadingPath,
): T | null => {
  let list: T[] = items;
  let value: T | undefined;
  for (const index of path) {
    value = list[index];
    if (!value) return null;
    list =
      value.type === "Group"
        ? (("rows" in value ? value.rows : value.columns) as T[])
        : [];
  }
  return value ?? null;
};
export const leafIndex = <T extends Row<any> | Column>(
  items: T[],
  path: HeadingPath,
): number | null => {
  const target = headingAt(items, path);
  if (!target) return null;
  return leaves(items).findIndex(
    (item) =>
      item === target ||
      (target.type === "Group" && leaves([target]).includes(item)),
  );
};
export const leafPath = <T extends Row<any> | Column>(
  items: T[],
  target: number,
  prefix: HeadingPath = [],
): HeadingPath | null => {
  let index = 0;
  for (let i = 0; i < items.length; i++) {
    const item = items[i]!;
    const path = [...prefix, i];
    if (item.type === "Individual") {
      if (index === target) return path;
      index += 1;
    } else {
      const children = ("rows" in item ? item.rows : item.columns) as T[];
      const count = leafCount(children);
      if (target < index + count)
        return leafPath(children, target - index, path);
      index += count;
    }
  }
  return null;
};
export const flatRows = <C extends GridCell>(
  rows: Row<C>[],
  path: HeadingPath = [],
  depth = 1,
  maxDepth = headingDepth(rows),
): {
  path: HeadingPath;
  row: Extract<Row<C>, { type: "Individual" }>;
  headings: {
    heading: string;
    path: HeadingPath;
    rowSpan: number;
    colSpan: number;
  }[];
}[] =>
  rows.flatMap((row, index) => {
    const next = [...path, index];
    if (row.type === "Group") {
      const children = flatRows(row.rows, next, depth + 1, maxDepth);
      children[0]?.headings.unshift({
        heading: row.heading,
        path: next,
        rowSpan: leafCount(row.rows),
        colSpan: 1,
      });
      return children;
    }
    return [
      {
        path: next,
        row,
        headings: [
          {
            heading: row.heading,
            path: next,
            rowSpan: 1,
            colSpan: maxDepth - depth + 1,
          },
        ],
      },
    ];
  });
export const headingDepth = <T extends Row<any> | Column>(items: T[]): number =>
  Math.max(
    1,
    ...items.map((item) =>
      item.type === "Group"
        ? 1 + headingDepth(("rows" in item ? item.rows : item.columns) as T[])
        : 1,
    ),
  );
export const cellRowspan = (cell: GridCell) => cell.rowspan ?? 1;
export const cellColspan = (cell: GridCell) => cell.colspan ?? 1;
const key = (row: number, column: number) => `${row},${column}`;
export const coveredCells = <C extends GridCell>(rows: Row<C>[]) => {
  const covered = new Map<string, [number, number]>();
  flatRows(rows).forEach(({ row }, rowIndex) =>
    row.cells.forEach((cell, column) => {
      if (covered.has(key(rowIndex, column))) return;
      for (let r = rowIndex; r < rowIndex + cellRowspan(cell); r++)
        for (let c = column; c < column + cellColspan(cell); c++)
          if (r !== rowIndex || c !== column)
            covered.set(key(r, c), [rowIndex, column]);
    }),
  );
  return covered;
};

const childItems = <T extends Row<any> | Column>(item: T): T[] =>
  item.type === "Group"
    ? (("rows" in item ? item.rows : item.columns) as T[])
    : [];
const pathsDepthFirst = <T extends Row<any> | Column>(
  items: T[],
  prefix: HeadingPath = [],
): HeadingPath[] =>
  items.flatMap((item, index) => {
    const path = [...prefix, index];
    return [path, ...pathsDepthFirst(childItems(item), path)];
  });
const pathsAtDepth = <T extends Row<any> | Column>(
  items: T[],
  depth: number,
  prefix: HeadingPath = [],
): HeadingPath[] =>
  items.flatMap((item, index) => {
    const path = [...prefix, index];
    const children = childItems(item);
    return depth === 1 || children.length === 0
      ? [path]
      : pathsAtDepth(children, depth - 1, path);
  });
const adjacentPath = (
  paths: HeadingPath[],
  path: HeadingPath,
  offset: -1 | 1,
): HeadingPath | null => {
  const index = paths.findIndex(
    (candidate) =>
      candidate.length === path.length &&
      candidate.every((part, i) => part === path[i]),
  );
  return index < 0 ? null : (paths[index + offset] ?? null);
};
const firstChildPath = <T extends Row<any> | Column>(
  items: T[],
  path: HeadingPath,
): HeadingPath | null => {
  const item = headingAt(items, path);
  return item && childItems(item).length > 0 ? [...path, 0] : null;
};
const lastLeafPath = <T extends Row<any> | Column>(
  items: T[],
): HeadingPath | null => leafPath(items, leafCount(items) - 1);
const samePath = (a: HeadingPath, b: HeadingPath) =>
  a.length === b.length && a.every((part, index) => part === b[index]);
const focusKey = (focus: Focus) => JSON.stringify(focus);
export const serializeFocus = focusKey;

export const movementFromKey = (
  event: Pick<KeyboardEvent, "key" | "shiftKey">,
): Movement | null => {
  if (event.key === "Tab") return event.shiftKey ? "ShiftTab" : "Tab";
  if (event.key === "Home" || event.key === "End") return event.key;
  if (event.key.startsWith("Arrow")) return event.key.slice(5) as Movement;
  return null;
};

/** Mirrors the phonology editor's spatial and tab-order navigation. */
export const moveFocus = <C extends GridCell>(
  body: Body<C>,
  focus: Focus,
  movement: Movement,
): Focus | null => {
  const rows = flatRows(body.rows);
  const covered = coveredCells(body.rows);
  const cellAt = (row: number, column: number): Focus => {
    const [anchorRow, anchorColumn] = covered.get(key(row, column)) ?? [
      row,
      column,
    ];
    return { type: "Cell", row: anchorRow, column: anchorColumn };
  };
  if (focus.type === "TopLeft") {
    if ((movement === "Right" || movement === "Tab") && body.columns.length)
      return { type: "ColumnHeading", path: [0] };
    if (movement === "Down" && body.rows.length)
      return { type: "RowHeading", path: [0] };
    if (movement === "End" && body.columns.length)
      return { type: "ColumnHeading", path: [body.columns.length - 1] };
    return movement === "ShiftTab" ? null : focus;
  }
  if (focus.type === "RowHeading") {
    const row = headingAt(body.rows, focus.path);
    if (!row) return focus;
    const first = focus.path.every((index) => index === 0);
    if (first && movement === "Up") return { type: "TopLeft" };
    if (movement === "Left")
      return focus.path.length > 1
        ? { type: "RowHeading", path: focus.path.slice(0, -1) }
        : focus;
    if (movement === "Home")
      return focus.path.length > 1
        ? { type: "RowHeading", path: [focus.path[0]!] }
        : { type: "TopLeft" };
    const rowIndex = leafIndex(body.rows, focus.path);
    if (movement === "End" && rowIndex !== null && leafCount(body.columns))
      return cellAt(rowIndex, leafCount(body.columns) - 1);
    if (
      row.type === "Individual" &&
      (movement === "Right" || movement === "Tab") &&
      rowIndex !== null &&
      row.cells.length
    )
      return cellAt(rowIndex, 0);
    if (row.type === "Group" && movement === "Right") {
      const child = firstChildPath(body.rows, focus.path);
      if (child) return { type: "RowHeading", path: child };
    }
    if (movement === "ShiftTab" && first) {
      const last = lastLeafPath(body.columns);
      return last ? { type: "ColumnHeading", path: last } : { type: "TopLeft" };
    }
    const paths =
      movement === "Tab" || movement === "ShiftTab"
        ? pathsDepthFirst(body.rows)
        : pathsAtDepth(body.rows, focus.path.length);
    const offset =
      movement === "Tab" || movement === "Down"
        ? 1
        : movement === "ShiftTab" || movement === "Up"
          ? -1
          : 0;
    const next = offset ? adjacentPath(paths, focus.path, offset) : null;
    return next ? { type: "RowHeading", path: next } : focus;
  }
  if (focus.type === "ColumnHeading") {
    const column = headingAt(body.columns, focus.path);
    if (!column) return focus;
    const first = focus.path.every((index) => index === 0);
    if (first && (movement === "Left" || movement === "ShiftTab"))
      return { type: "TopLeft" };
    const last = lastLeafPath(body.columns);
    if (movement === "Tab" && last && samePath(last, focus.path))
      return body.rows.length ? { type: "RowHeading", path: [0] } : null;
    if (movement === "Up" && focus.path.length > 1)
      return { type: "ColumnHeading", path: focus.path.slice(0, -1) };
    const columnIndex = leafIndex(body.columns, focus.path);
    if (
      column.type === "Individual" &&
      movement === "Down" &&
      columnIndex !== null &&
      rows.length
    )
      return cellAt(0, columnIndex);
    if (column.type === "Group" && movement === "Down") {
      const child = firstChildPath(body.columns, focus.path);
      if (child) return { type: "ColumnHeading", path: child };
    }
    const paths =
      movement === "Tab" || movement === "ShiftTab"
        ? pathsDepthFirst(body.columns)
        : pathsAtDepth(body.columns, focus.path.length);
    const offset =
      movement === "Tab" || movement === "Right"
        ? 1
        : movement === "ShiftTab" || movement === "Left"
          ? -1
          : 0;
    const next = offset ? adjacentPath(paths, focus.path, offset) : null;
    return next ? { type: "ColumnHeading", path: next } : focus;
  }
  const anchor = cellAt(focus.row, focus.column) as Extract<
    Focus,
    { type: "Cell" }
  >;
  const cell = rows[anchor.row]?.row.cells[anchor.column];
  if (!cell) return focus;
  const rowSpan = cellRowspan(cell),
    columnSpan = cellColspan(cell);
  const lastRow = anchor.row + rowSpan >= rows.length;
  const lastColumn = anchor.column + columnSpan >= leafCount(body.columns);
  if (movement === "Up")
    return anchor.row > 0
      ? cellAt(anchor.row - 1, anchor.column)
      : { type: "ColumnHeading", path: leafPath(body.columns, anchor.column)! };
  if (movement === "Down")
    return lastRow ? focus : cellAt(anchor.row + rowSpan, anchor.column);
  if (movement === "Left" || movement === "ShiftTab")
    return anchor.column > 0
      ? cellAt(anchor.row, anchor.column - 1)
      : { type: "RowHeading", path: rows[anchor.row]!.path };
  if (movement === "Right")
    return lastColumn ? focus : cellAt(anchor.row, anchor.column + columnSpan);
  if (movement === "Home")
    return { type: "RowHeading", path: rows[anchor.row]!.path };
  if (movement === "End")
    return cellAt(anchor.row, leafCount(body.columns) - 1);
  if (movement === "Tab") {
    if (lastRow && lastColumn) return null;
    if (!lastColumn) return cellAt(anchor.row, anchor.column + columnSpan);
    const next = adjacentPath(
      pathsDepthFirst(body.rows),
      rows[anchor.row]!.path,
      1,
    );
    return next ? { type: "RowHeading", path: next } : null;
  }
  return focus;
};
const mapRows = <C extends GridCell>(
  rows: Row<C>[],
  fn: (cell: C, row: number, column: number) => C,
): Row<C>[] => {
  let rowIndex = 0;
  const visit = (items: Row<C>[]): Row<C>[] =>
    items.map((row) => {
      if (row.type === "Group") return { ...row, rows: visit(row.rows) };
      const current = rowIndex++;
      return {
        ...row,
        cells: row.cells.map((cell, column) => fn(cell, current, column)),
      };
    });
  return visit(rows);
};
const setHeading = <T extends Row<any> | Column>(
  items: T[],
  path: HeadingPath,
  replacement: T,
): T[] =>
  items.map((item, index) =>
    index !== path[0]
      ? item
      : path.length === 1
        ? replacement
        : item.type === "Group"
          ? ({
              ...item,
              ...("rows" in item
                ? {
                    rows: setHeading(
                      item.rows as T[],
                      path.slice(1),
                      replacement,
                    ),
                  }
                : {
                    columns: setHeading(
                      item.columns as T[],
                      path.slice(1),
                      replacement,
                    ),
                  }),
            } as T)
          : item,
  );
const spliceHeading = <T extends Row<any> | Column>(
  items: T[],
  path: HeadingPath,
  remove: number,
  replacement: T[],
): T[] => {
  if (path.length === 1) {
    const copy = [...items];
    copy.splice(path[0]!, remove, ...replacement);
    return copy;
  }
  return items.map((item, index) =>
    index !== path[0]
      ? item
      : item.type === "Group"
        ? ({
            ...item,
            ...("rows" in item
              ? {
                  rows: spliceHeading(
                    item.rows as T[],
                    path.slice(1),
                    remove,
                    replacement,
                  ),
                }
              : {
                  columns: spliceHeading(
                    item.columns as T[],
                    path.slice(1),
                    remove,
                    replacement,
                  ),
                }),
          } as T)
        : item,
  );
};
const collapse = <T extends Row<any> | Column>(items: T[]): T[] =>
  items.map((item) => {
    if (item.type !== "Group") return item;
    const children = collapse(
      ("rows" in item ? item.rows : item.columns) as T[],
    );
    if (children.length === 1)
      return { ...children[0]!, heading: item.heading } as T;
    return {
      ...item,
      ...("rows" in item ? { rows: children } : { columns: children }),
    } as T;
  });
const adjustColumns = <C extends GridCell>(
  rows: Row<C>[],
  index: number,
  delta: 1 | -1,
): Row<C>[] =>
  mapRows(rows, (cell, _row, column) => {
    const span = cellColspan(cell);
    if (delta > 0 && column < index && index < column + span)
      return { ...cell, colspan: span + 1 };
    if (delta < 0 && column < index && index < column + span)
      return { ...cell, colspan: Math.max(1, span - 1) };
    return cell;
  });
const adjustRows = <C extends GridCell>(
  rows: Row<C>[],
  index: number,
  delta: 1 | -1,
): Row<C>[] =>
  mapRows(rows, (cell, row) => {
    const span = cellRowspan(cell);
    if (delta > 0 && row < index && index < row + span)
      return { ...cell, rowspan: span + 1 };
    if (delta < 0 && row < index && index < row + span)
      return { ...cell, rowspan: Math.max(1, span - 1) };
    return cell;
  });
const adjustColumnsForRemove = <C extends GridCell>(
  rows: Row<C>[],
  index: number,
  count: number,
): Row<C>[] =>
  mapRows(rows, (cell, _row, column) => {
    if (column >= index) return cell;
    const span = cellColspan(cell);
    const overlap = Math.max(0, Math.min(column + span, index + count) - index);
    return overlap ? { ...cell, colspan: Math.max(1, span - overlap) } : cell;
  });
const adjustRowsForRemove = <C extends GridCell>(
  rows: Row<C>[],
  index: number,
  count: number,
): Row<C>[] =>
  mapRows(rows, (cell, row) => {
    if (row >= index) return cell;
    const span = cellRowspan(cell);
    const overlap = Math.max(0, Math.min(row + span, index + count) - index);
    return overlap ? { ...cell, rowspan: Math.max(1, span - overlap) } : cell;
  });
const insertCell = <C extends GridCell>(
  rows: Row<C>[],
  index: number,
  createCell: () => C,
): Row<C>[] =>
  rows.map((row) =>
    row.type === "Group"
      ? { ...row, rows: insertCell(row.rows, index, createCell) }
      : {
          ...row,
          cells: [
            ...row.cells.slice(0, index),
            createCell(),
            ...row.cells.slice(index),
          ],
        },
  );
const removeCells = <C extends GridCell>(
  rows: Row<C>[],
  index: number,
  count: number,
): Row<C>[] =>
  rows.map((row) =>
    row.type === "Group"
      ? { ...row, rows: removeCells(row.rows, index, count) }
      : {
          ...row,
          cells: [
            ...row.cells.slice(0, index),
            ...row.cells.slice(index + count),
          ],
        },
  );
const setCell = <C extends GridCell>(
  rows: Row<C>[],
  row: number,
  column: number,
  cell: C,
): Row<C>[] => {
  let current = 0;
  const visit = (items: Row<C>[]): Row<C>[] =>
    items.map((item) => {
      if (item.type === "Group") return { ...item, rows: visit(item.rows) };
      return {
        ...item,
        cells:
          current++ === row
            ? item.cells.map((value, index) =>
                index === column ? cell : value,
              )
            : item.cells,
      };
    });
  return visit(rows);
};
const snapshot = <C extends GridCell>(state: State<C>): Snapshot<C> => ({
  body: state.body,
  focus: state.focus,
  select: state.select,
});
export const initialState = <C extends GridCell>(body: Body<C>): State<C> => ({
  body,
  focus: { type: "Cell", row: 0, column: 0 },
  select: null,
  undoStack: [],
  redoStack: [],
});
export const apply = <C extends GridCell>(
  state: State<C>,
  action: Action<C>,
  options: Options<C>,
): State<C> => {
  if (action.type === "Undo") {
    const previous = state.undoStack.at(-1);
    return previous
      ? {
          ...previous,
          undoStack: state.undoStack.slice(0, -1),
          redoStack: [snapshot(state), ...state.redoStack],
        }
      : state;
  }
  if (action.type === "Redo") {
    const next = state.redoStack[0];
    return next
      ? {
          ...next,
          undoStack: [...state.undoStack, snapshot(state)],
          redoStack: state.redoStack.slice(1),
        }
      : state;
  }
  if (action.type === "Focus") return { ...state, focus: action.focus };
  if (action.type === "Select") return { ...state, select: action.select };
  let body = state.body;
  if (action.type === "SetCell")
    body = {
      ...body,
      rows: setCell(body.rows, action.row, action.column, action.cell),
    };
  if (action.type === "EditHeading") {
    const items = (action.kind === "row" ? body.rows : body.columns) as any[];
    const target = headingAt(items, action.path);
    if (!target) return state;
    const next = setHeading(items, action.path, {
      ...target,
      heading: action.heading,
      autogenerated: false,
    });
    body =
      action.kind === "row"
        ? { ...body, rows: next as Row<C>[] }
        : { ...body, columns: next as Column[] };
  }
  if (
    action.type === "AddHeading" ||
    action.type === "DeleteHeading" ||
    action.type === "SplitHeading"
  ) {
    const items = (action.kind === "row" ? body.rows : body.columns) as any[];
    const target = headingAt(items, action.path);
    const index = leafIndex(items, action.path);
    if (!target || index === null) return state;
    const count = leafCount([target]);
    if (action.type === "AddHeading") {
      const offset = action.position === "before" ? index : index + count;
      const insertPath = [
        ...action.path.slice(0, -1),
        action.path.at(-1)! + (action.position === "before" ? 0 : 1),
      ];
      if (action.kind === "row") {
        const row: Row<C> = {
          type: "Individual",
          heading: "New Row",
          autogenerated: true,
          cells: Array.from(
            { length: leafCount(body.columns) },
            options.createCell,
          ),
        };
        body = {
          ...body,
          rows: spliceHeading(adjustRows(body.rows, offset, 1), insertPath, 0, [
            row,
          ]),
        };
      } else {
        const column: Column = {
          type: "Individual",
          heading: "New Column",
          autogenerated: true,
        };
        body = {
          ...body,
          columns: spliceHeading(body.columns, insertPath, 0, [column]),
          rows: insertCell(
            adjustColumns(body.rows, offset, 1),
            offset,
            options.createCell,
          ),
        };
      }
    }
    if (action.type === "DeleteHeading") {
      if (action.kind === "row")
        body = {
          ...body,
          rows: collapse(
            spliceHeading(
              adjustRowsForRemove(body.rows, index, count),
              action.path,
              1,
              [],
            ),
          ),
        };
      else
        body = {
          ...body,
          columns: collapse(spliceHeading(body.columns, action.path, 1, [])),
          rows: removeCells(
            adjustColumnsForRemove(body.rows, index, count),
            index,
            count,
          ),
        };
    }
    if (action.type === "SplitHeading") {
      if (action.kind === "row") {
        const newRow: Row<C> = {
          type: "Individual",
          heading: "New Row",
          autogenerated: true,
          cells: Array.from(
            { length: leafCount(body.columns) },
            options.createCell,
          ),
        };
        const original = target as unknown as Row<C>;
        const group: Row<C> =
          original.type === "Individual"
            ? {
                type: "Group",
                heading: original.heading,
                autogenerated: original.autogenerated,
                rows: [
                  { ...original, heading: "New Row", autogenerated: true },
                  newRow,
                ],
              }
            : {
                type: "Group",
                heading: "New Group",
                autogenerated: true,
                rows: [original, newRow],
              };
        body = {
          ...body,
          rows: spliceHeading(
            adjustRows(body.rows, index + count, 1),
            action.path,
            1,
            [group],
          ),
        };
      } else {
        const newColumn: Column = {
          type: "Individual",
          heading: "New Column",
          autogenerated: true,
        };
        const original = target as unknown as Column;
        const group: Column =
          original.type === "Individual"
            ? {
                type: "Group",
                heading: original.heading,
                autogenerated: original.autogenerated,
                columns: [
                  { ...original, heading: "New Column", autogenerated: true },
                  newColumn,
                ],
              }
            : {
                type: "Group",
                heading: "New Group",
                autogenerated: true,
                columns: [original, newColumn],
              };
        body = {
          ...body,
          columns: spliceHeading(body.columns, action.path, 1, [group]),
          rows: insertCell(
            adjustColumns(body.rows, index + count, 1),
            index + count,
            options.createCell,
          ),
        };
      }
    }
  }
  if (action.type === "Merge") {
    const grid = flatRows(body.rows).map(({ row }) => row.cells);
    const covered = coveredCells(body.rows);
    const region = (row: number, column: number) => {
      const [top, left] = covered.get(key(row, column)) ?? [row, column];
      const anchor = grid[top]?.[left];
      return {
        top,
        left,
        bottom: top + cellRowspan(anchor ?? {}) - 1,
        right: left + cellColspan(anchor ?? {}) - 1,
      };
    };
    const first = region(action.first.row, action.first.column),
      second = region(action.second.row, action.second.column);
    let top = Math.min(first.top, second.top),
      bottom = Math.max(first.bottom, second.bottom),
      left = Math.min(first.left, second.left),
      right = Math.max(first.right, second.right);
    let changed = true;
    while (changed) {
      changed = false;
      grid.forEach((cells, row) =>
        cells.forEach((cell, column) => {
          if (
            covered.has(key(row, column)) ||
            (cellRowspan(cell) === 1 && cellColspan(cell) === 1)
          )
            return;
          const candidate = region(row, column);
          const intersects =
            left <= candidate.right &&
            candidate.left <= right &&
            top <= candidate.bottom &&
            candidate.top <= bottom;
          const contained =
            top <= candidate.top &&
            left <= candidate.left &&
            bottom >= candidate.bottom &&
            right >= candidate.right;
          if (intersects && !contained) {
            top = Math.min(top, candidate.top);
            bottom = Math.max(bottom, candidate.bottom);
            left = Math.min(left, candidate.left);
            right = Math.max(right, candidate.right);
            changed = true;
          }
        }),
      );
    }
    const anchor = grid[top]?.[left];
    if (!anchor) return state;
    const values: C[] = [];
    for (let row = top; row <= bottom; row++)
      for (let column = left; column <= right; column++)
        if (!covered.has(key(row, column)) && grid[row]?.[column])
          values.push(grid[row]![column]!);
    body = {
      ...body,
      rows: mapRows(body.rows, (cell, row, column) =>
        row < top || row > bottom || column < left || column > right
          ? cell
          : row === top && column === left
            ? {
                ...options.mergeCells(anchor, values),
                rowspan: bottom - top + 1,
                colspan: right - left + 1,
              }
            : options.createCell(),
      ),
    };
  }
  if (action.type === "Unmerge") {
    const grid = flatRows(body.rows).map(({ row }) => row.cells);
    const covered = coveredCells(body.rows);
    const [top, left] = covered.get(key(action.row, action.column)) ?? [
      action.row,
      action.column,
    ];
    const anchor = grid[top]?.[left];
    if (!anchor || (cellRowspan(anchor) === 1 && cellColspan(anchor) === 1))
      return state;
    body = {
      ...body,
      rows: mapRows(body.rows, (cell, row, column) =>
        row >= top &&
        row < top + cellRowspan(anchor) &&
        column >= left &&
        column < left + cellColspan(anchor)
          ? row === top && column === left
            ? { ...cell, rowspan: undefined, colspan: undefined }
            : options.createCell()
          : cell,
      ),
    };
  }
  return {
    ...state,
    body,
    undoStack: [...state.undoStack, snapshot(state)],
    redoStack: [],
  };
};
