import type { Body, Column, GridCell, Row } from "./table-editor-core";

export const invalid = (path: string, message: string): never => {
  throw new Error(`${path}: ${message}`);
};

export const object = (
  value: unknown,
  path: string,
): Record<string, unknown> => {
  if (typeof value !== "object" || value === null || Array.isArray(value))
    return invalid(path, "expected an object.");
  return value as Record<string, unknown>;
};

export const array = (value: unknown, path: string): unknown[] => {
  if (!Array.isArray(value)) return invalid(path, "expected an array.");
  return value;
};

export const string = (value: unknown, path: string): string => {
  if (typeof value !== "string") return invalid(path, "expected a string.");
  return value;
};

const span = (value: unknown, path: string): number | undefined => {
  if (value === undefined) return undefined;
  if (
    typeof value !== "number" ||
    !Number.isInteger(value) ||
    value < 1 ||
    value > 0xffffffff
  )
    return invalid(path, "expected a positive integer.");
  return value;
};

export const parseJson = (source: string): unknown => {
  try {
    return JSON.parse(source.replace(/^\uFEFF/, ""));
  } catch {
    throw new Error("This file is not valid JSON.");
  }
};

// Both table editors use the same heading and merged-cell layout.
export const parseGridBody = <C extends GridCell>(
  value: unknown,
  options: {
    parseCell: (value: Record<string, unknown>, path: string) => C;
    isEmpty: (cell: C) => boolean;
    maxDepth?: number;
  },
): Body<C> => {
  const body = object(value, "Table body");

  const heading = (value: unknown, path: string) => {
    const item = object(value, path);
    if (item.type !== "Individual" && item.type !== "Group")
      return invalid(path, 'type must be "Individual" or "Group".');
    if (
      item.autogenerated !== undefined &&
      typeof item.autogenerated !== "boolean"
    )
      return invalid(`${path}.autogenerated`, "expected a boolean.");
    return {
      item,
      heading: string(item.heading, `${path}.heading`),
      autogenerated: item.autogenerated as boolean | undefined,
    };
  };

  let columnCount = 0;
  const columns = (value: unknown, path: string, depth = 0): Column[] => {
    if (depth >= (options.maxDepth ?? 101))
      return invalid(path, "headings are nested too deeply.");
    return array(value, path).map((value, i): Column => {
      const location = `${path}[${i}]`;
      const { item, ...properties } = heading(value, location);
      if (item.type === "Group") {
        const children = columns(
          item.columns,
          `${location}.columns`,
          depth + 1,
        );
        if (!children.length)
          return invalid(location, "a group must contain columns.");
        return { type: "Group", ...properties, columns: children };
      }
      columnCount++;
      return { type: "Individual", ...properties };
    });
  };
  const parsedColumns = columns(body.columns, "columns");

  const grid: C[][] = [];
  const rows = (value: unknown, path: string, depth = 0): Row<C>[] => {
    if (depth >= (options.maxDepth ?? 101))
      return invalid(path, "headings are nested too deeply.");
    return array(value, path).map((value, i): Row<C> => {
      const location = `${path}[${i}]`;
      const { item, ...properties } = heading(value, location);
      if (item.type === "Group") {
        const children = rows(item.rows, `${location}.rows`, depth + 1);
        if (!children.length)
          return invalid(location, "a group must contain rows.");
        return { type: "Group", ...properties, rows: children };
      }
      const values = array(item.cells, `${location}.cells`);
      if (values.length !== columnCount)
        return invalid(
          location,
          `expected ${columnCount} cells, found ${values.length}.`,
        );
      const cells = values.map((value, j): C => {
        const path = `${location}.cells[${j}]`;
        const cell = object(value, path);
        return {
          ...options.parseCell(cell, path),
          rowspan: span(cell.rowspan, `${path}.rowspan`),
          colspan: span(cell.colspan, `${path}.colspan`),
        };
      });
      grid.push(cells);
      return { type: "Individual", ...properties, cells };
    });
  };
  const parsedRows = rows(body.rows, "rows");
  const occupied = grid.map(() => Array<boolean>(columnCount).fill(false));
  grid.forEach((cells, r) => {
    cells.forEach((cell, c) => {
      const path = `Cell in row ${r + 1}, column ${c + 1}`;
      const rowspan = cell.rowspan ?? 1;
      const colspan = cell.colspan ?? 1;
      if (occupied[r]![c]) {
        if (!options.isEmpty(cell))
          return invalid(path, "cells covered by a merged cell must be empty.");
        if (rowspan !== 1 || colspan !== 1)
          return invalid(path, "merged cells cannot overlap.");
        return;
      }
      if (r + rowspan > grid.length || c + colspan > columnCount)
        return invalid(path, "merged cells cannot extend past the table edge.");
      for (let row = r; row < r + rowspan; row++) {
        for (let column = c; column < c + colspan; column++) {
          if (occupied[row]![column])
            return invalid(path, "merged cells cannot overlap.");
          occupied[row]![column] = true;
        }
      }
    });
  });
  return { rows: parsedRows, columns: parsedColumns };
};

export const serializeJson = (value: unknown): string =>
  JSON.stringify(value, null, 2) + "\n";
