on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  nix-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-compose-action@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt install just graphviz
      - run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
      - run: just test