on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  nix-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-compose-action@v1
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/nix-flake-checker-action@main
      - run: nix shell . --command "just test"